name: Deploy Gitabsa Website

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Cambia la versión de Node.js si es necesario

    - name: Install dependencies
      run: npm install  # Asegúrate de tener un package.json si usas Node.js

    - name: Build the project
      run: npm run build  # Cambia esto si usas un comando diferente para construir tu sitio

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Cambia esto al directorio que contiene tu sitio construido
